# 构建所需的语言环境
language: node_js
# 构建所需要的node版本
node_js:
  - "v14.17.0"
branches:
  only:
    - main    # 构建的分支
cache:
  directories:
    - node_modules # 依赖缓存的目录
before_install:
  - export TZ='Asia/Shanghai'  # 设置时区
  - rm -rf package-lock.json
  - rm -rf yarn.lock
install:
  - yarn # 安装编译工具
script:
  - yarn build
after_script:
  - cd ./build
  - git init
  - git config user.name lixingjuan
  - git config user.email 18236129679@163.com
  - git add .
  - git commit -m "Update build"
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/lixingjuan/react-playground" master:gh-pages
deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN # github 上的token环境变量
  # local_dir: build ## 根据情况自定义到静态文件输出目录
  # project: ./build/
  target_branch: gh-pages
  verbose: true
  on:
    branch: main

