import { Options } from "highcharts/highcharts.d";
import { omit, pick } from "lodash";

const res: Options = {
  /* @ts-ignore-next-lint */
  /* @ts-ignore-next-lint */
  chart: { type: "line", step: false, spacing: [25] },
  /* @ts-ignore-next-lint */
  title: { text: null },
  colors: [
    "#5180ff",
    "#ff9749",
    "#1abfb0",
    "#2d3966",
    "#f44949",
    "#f8cb01",
    "#23a6ff",
    "#5f4598",
    "#059184",
    "#4c3124",
    "#5a9b56",
    "#333ad1",
    "#ffa493",
    "#dabc74",
    "#0b3c45",
    "#8a50cc",
    "#3a47b5",
    "#c9751c",
    "#0e7ab2",
    "#095d2d",
    "#91a71b",
    "#a6775f",
    "#d16056",
    "#487ac9",
    "#2ec2d7",
    "#cdbe1b",
    "#a94242",
    "#6250bb",
    "#6d9bea",
    "#7dc9ce",
    "#ede871",
    "#e69563",
  ],
  credits: { enabled: false },
  legend: { enabled: false },
  exporting: { enabled: false },
  plotOptions: {
    line: {
      marker: {
        enabled: true,
        radius: 3,
        states: { hover: { radius: 4 } },
        symbol: "circle",
      },
      /* @ts-ignore-next-lint */
      connectnulls: true,
    },
    spline: {
      marker: {
        enabled: true,
        radius: 3,
        states: { hover: { radius: 4 } },
        symbol: "circle",
      },
      /* @ts-ignore-next-lint */
      connectnulls: true,
    },
    areaspline: {
      marker: {
        enabled: true,
        radius: 0,
        states: { hover: { radius: 4 } },
      },
    },
    column: { minPointLength: 2 },
    series: {
      animation: false,
      turboThreshold: 100000,
      lineWidth: 2,
      states: {
        hover: { lineWidth: 3 },
        inactive: { enabled: false, opacity: 1 },
      },
      dataGrouping: { enabled: true },
      /* @ts-ignore-next-lint */
      connectnulls: true,
    },
  },
  xAxis: {
    type: "category",
    dateTimeLabelFormats: {
      millisecond: "%H:%M",
      second: "%H:%M",
      minute: "%H:%M",
      hour: "%H:%M",
      day: "%m-%d",
      week: "%m-%d",
      month: "%Y-%m",
      year: "%Y",
    },
    lineColor: "#e5e5e5",
    lineWidth: 1,
    tickLength: 5,
    tickWidth: 1,
    tickColor: "#e5e5e5",
    tickPixelInterval: 120,
    labels: { style: { color: "#666666", fontSize: "12px" } },
    categories: [
      "1月",
      "2月",
      "3月",
      "4月",
      "5月",
      "6月",
      "7月",
      "8月",
      "9月",
      "10月",
      "11月",
      "12月",
    ],
  },
  /* @ts-ignore-next-lint */
  yAxis: {
    title: { text: "", style: { color: "#333", fontSize: "12px" } },
    labels: { x: -5, style: { color: "#666666", fontSize: "12px" } },
    lineWidth: 0,
    lineColor: "#c8c8c8",
    gridLineDashStyle: "dash",
    gridLineColor: "#e9e9e9",
    gridLineWidth: 1,
    opposite: false,
  },
  navigator: {
    enabled: false,
    outlineColor: "#ddd",
    series: { color: "#E3E8EC" },
    maskFill: "rgba(211, 229, 247, 0.2)",
    handles: { backgroundColor: "#95C9EF", borderColor: "#fff" },
    xAxis: {
      type: "datetime",
      dateTimeLabelFormats: {
        millisecond: "%H:%M",
        second: "%H:%M",
        minute: "%H:%M",
        hour: "%H:%M",
        day: "%m-%d",
        week: "%m-%d",
        month: "%Y-%m",
        year: "%Y",
      },
    },
    height: 26,
  },
  tooltip: {
    enabled: true,
    shadow: false,
    crosshairs: [{ width: 1.5, color: "#ccc" }],
    shared: true,
    useHTML: true,
    /* @ts-ignore-next-lint */
    style: { padding: 0 },
    hideDelay: 100,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderWidth: 1,
    /* @ts-ignore-next-lint */
    borderRadius: "4",
    borderColor: "#E9E9E9",
    split: false,
  },
  series: [
    {
      name: "2014",
      data: [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      type: "line",
      /* @ts-ignore-next-lint */
      step: false,
    },
    {
      name: "2015",
      data: [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      type: "line",
      /* @ts-ignore-next-lint */
      step: false,
    },
    {
      name: "2016",
      data: [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      type: "line",
      /* @ts-ignore-next-lint */
      step: false,
    },
    {
      name: "2017",
      data: [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
      ],
      type: "line",
      /* @ts-ignore-next-lint */
      step: false,
    },
    {
      name: "2018",
      data: [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        258808.9,
      ],
      type: "line",
      /* @ts-ignore-next-lint */
      step: false,
      accuracy: 2,
    },
    {
      name: "2019",
      data: [
        null,
        null,
        217168.3,
        null,
        null,
        241502.6,
        null,
        null,
        251046.3,
        null,
        null,
        276798,
      ],
      type: "line",
      /* @ts-ignore-next-lint */
      step: false,
      accuracy: 2,
    },
    {
      name: "2020",
      data: [
        null,
        null,
        205727,
        null,
        null,
        248985.1,
        null,
        null,
        264976.3,
        null,
        null,
        296297.8,
      ],
      type: "line",
      /* @ts-ignore-next-lint */
      step: false,
      accuracy: 2,
    },
    {
      name: "2021",
      data: [
        null,
        null,
        249310.1,
        null,
        null,
        282857.4,
        null,
        null,
        290963.8,
        null,
        null,
        null,
      ],
      type: "line",
      /* @ts-ignore-next-lint */
      step: false,
      accuracy: 2,
    },
  ],
};

// export default pick(res, ["xAxis", "yAxis", "series"]);
export default omit(res);
